# Generated by Django 5.1.6 on 2025-03-06 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
